### ISSUE TITLE
Updates for amplify?

### ISSUE THREAD

**Issue by jagthedrummer** [adopted-ember-addons/ember-cognito#104]
It looks like `amazon-cognito-identity-js` is deprecated and Amazon in encouraging folks to use `amplify-js`. Are there plans to update this add-one to use amplify? If so, how could I help with that effort?

**Comment by paulcwatts** [comment]
There's definitely the desire to upgrade, but no firm plans yet. I haven't had much time for open source work in the past few weeks.

A few things to think about, off the top of my head:

1. I haven't done much investigation into the library yet so I don't know how we'd go about importing the code. Apparently someone has already starting doing this: https://itnext.io/adding-aws-amplify-to-an-ember-js-application-72683167c476
2. How to migrate the existing configuration to what Amplify requires?
3. Can we use the `Auth` module? My concern is being able to properly store the access tokens and so forth in `ember-simple-auth`s storage.

**Comment by jagthedrummer** [comment]
I've only done a little bit of testing, but so far I've had good luck getting Amplify into my Ember project with this add-on: https://github.com/grimbonious/ember-cli-amplify

I hoping to do some more work on it over the weekend.

**Comment by jagthedrummer** [comment]
Just for reference, here's a quick and dirty login controller that I just got to work with the `ember-cli-amplify` add-on. It uses the `Auth` module from Amplify to sign in, but doesn't store anything in the session or interact with `ember-simple-auth`.

```javascript
import { equal } from '@ember/object/computed';
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';
import { set, getProperties, get } from '@ember/object';
import { readOnly } from '@ember/object/computed';

export default Controller.extend({
  amplify:service(),

  actions: {
    login(e) {
      e.preventDefault();
      let params = getProperties(this, 'username', 'password');
      this.authenticate(params);
    }
  },

  authenticate(params) {
    const auth = this.get('amplify').Auth;
    auth.signIn(params.username, params.password)
      .then((user) => {
        console.log('got a user!',user);
        this.transitionToRoute('/');
      })
      .catch((err) => {
        console.log('got an err :( ',err);
      });
  }
});
```

**Comment by jagthedrummer** [comment]
For further reference, here's a super simple `ember-simple-auth` authenticator that I got working with `ember-cli-amplify`:

```js
//app/authenticators/amplify.js
import Base from 'ember-simple-auth/authenticators/base';
import { inject as service } from '@ember/service';
import { resolve, reject, Promise } from 'rsvp';

export default Base.extend({
  amplify:service(),

  async restore(data) {
    return new Promise(async (resolve, reject) => {
      const auth = this.get('amplify').Auth;
      let session = await auth.currentSession();
      if(session){
        let idToken = session.idToken.jwtToken;
        let accessToken = session.accessToken.jwtToken;
        let email = session.idToken.payload.email
        resolve({ idToken, accessToken, email });
      }else{
        reject('no session found in amplify...');
      }
    });

  },

  async authenticate(params) {
    const auth = this.get('amplify').Auth;
    return new Promise(async (resolve, reject) => {
      auth.signIn(params.username, params.password)
      .then(async (user) => {
        let session = await auth.currentSession();
        let idToken = session.idToken.jwtToken;
        let accessToken = session.accessToken.jwtToken;
        let email = session.idToken.payload.email
        resolve({ idToken, accessToken, email });
      })
      .catch((err) => {
        reject(err);
      });
    });
  },

  invalidate(data) {
    const auth = this.get('amplify').Auth;
    return auth.signOut();
  }
});
```

And it's working with this application adapter:

```js
//app/adapters/application.js
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
import { isPresent } from '@ember/utils';
import { inject as service } from '@ember/service';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  host: 'https://octyyhf02h.execute-api.us-east-1.amazonaws.com',
  namespace: 'dev',

  session: service(),
  amplify: service(),

  authorize(xhr) {
    let auth = this.get('amplify').Auth;
    let id_token = this.get('session.data.authenticated.idToken');
    let access_token = this.get('session.data.authenticated.accessToken');
    if (id_token) {
      xhr.setRequestHeader('Authorization', id_token);
    }
  }
});
```

And this login controller:

```js
// app/controllers/login.js
import { equal } from '@ember/object/computed';
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';
import { set, getProperties, get } from '@ember/object';
import { readOnly } from '@ember/object/computed';

export default Controller.extend({
  session: service(),

  actions: {
    login(e) {
      e.preventDefault();
      let params = getProperties(this, 'username', 'password');
      this.authenticate(params);
    },

    newPassword(e) {
      e.preventDefault();
      let { newPassword, state } = getProperties(this, 'newPassword', 'state');
      this.authenticate({ password: newPassword, state });
    }
  },

  authenticate(params) {
    get(this, 'session').authenticate('authenticator:amplify', params).then((user) => {
      this.transitionToRoute('notes');
    }).catch((err) => {
      if (err.state && err.state.name === 'newPasswordRequired') {
        set(this, 'errorMessage', '');
        set(this, 'state', err.state);
      } else {
        set(this, 'errorMessage', err.message || err);
      }
    });
  }
});
```

**Comment by paulcwatts** [comment]
That looks great! 💯  It's good to know it could be this easy. If I get some time for open source work soon, this is a great start. Or, if you want to look into creating a PR, that would be even more appreciated :)

**Comment by paulcwatts** [comment]
Hi @jagthedrummer, I finally got around to switching this library to use amplify. If you are still using this library, I'd appreciate some testing or feedback!

**Comment by stephankaag** [comment]
@paulcwatts Is Amplify's CookieStorage supported? This would be a requirement for projects using SSR/Fastboot where localStorage is unavailable.

**Comment by paulcwatts** [comment]
Hi @stephankaag, I don't see anywhere that Amplify says it supports cookie storage. Do you mean ember-simple-auth's CookieStorage?

**Comment by stephankaag** [comment]
@paulcwatts No, I mean Amplify. Look for 'cookieStorage' on https://aws-amplify.github.io/docs/js/authentication.

**Comment by paulcwatts** [comment]
Thanks for the link. I haven't tested it, but I suppose it could work. You can configure Amplify this way, as well as configure ember-simple-auth to use cookie storage. 

Though you should note that there are limitations due to the amount of data Amplify attempts to store in a cookie: https://github.com/aws-amplify/amplify-js/issues/1545. I noticed this when this library used to override the Cognito storage to use ember-simple-auth's cookie storage.

**Comment by paulcwatts** [comment]
Just FYI, I workaround these issues in my Fastboot app by doing a couple things:

1. Replacing ember-simple-auth's session storage with one that doesn't do anything in Fastboot. Effectively, in Fastboot, the user is never logged in.
2. For any route hook that requires a user, I delay any rendering in Fastboot -- the Fastboot route renders a basic "loading" page which then gets replaced when the browser app launches.

This works well enough for my use case, but it has its obvious drawbacks and may not work for your use case.

**Comment by rwwagner90** [comment]
@jagthedrummer is everything in this addon up to date and working for you now?

**Comment by jagthedrummer** [comment]
@rwwagner90 I don't currently have an app using this addon. I was exploring it for a project a few years ago, and ended up going a different direction.

**Comment by rwwagner90** [comment]
I'm going to close this as wontfix, since I think things may already be working. Please feel free to open new issues if anyone is still having issues with this!
